services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acadex
    ports:
      - "5432:5432"
    volumes:
      - acadex_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push --accept-data-loss && node dist/prisma/seed.js && node dist/src/index.js"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5432/acadex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev_jwt_secret_do_not_use_in_prod_12345678
      FRONTEND_URL: "http://localhost"
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - local_storage:/app/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  acadex_db_data:
  local_storage:
