
export const ANCILLARY_ROLES = [
  'Tuckshop Manager',
  'Cashier',
  'Tuckshop Assistant',
  'Boarding Master',
  'Hostel Matron',
  'Hostel Supervisor',
  'Security Guard',
  'Security Supervisor',
  'Night Watchman',
  'Gate Officer',
  'Head Chef',
  'Cook',
  'Catering Supervisor',
  'Kitchen Assistant',
  'ICT Technician',
  'Network Administrator',
  'Systems Support',
  'Driver',
  'Transport Coordinator',
  'Sports Coordinator',
  'Sports Master',
  'Maintenance Supervisor',
  'Plumber',
  'Electrician',
  'Carpenter',
  'General Maintenance Worker',
  'Library Assistant',
  'SDC Representative',
  'Procurement Officer',
  'Cleaner Lead',
  'Groundskeeper',
  'First Aider',
  'Sports Captain',
  'DH Captain',
  'House Master',
  'House Captain',
  'Church Prefect',
  'School Chaplain',
  'Head Boy',
  'Head Girl',
  'Vice Head Boy',
  'Vice Head Girl',
  'Senior Prefect',
  'Prefect',
  'Class Monitor',
  'Student Librarian',
  'Farm Manager',
  'Farm Assistant',
  'Agriculture Teacher'
];

export const ROLE_GROUPS = {
  TUCKSHOP: ['Tuckshop Manager', 'Cashier', 'Tuckshop Assistant'],
  BOARDING: ['Boarding Master', 'Hostel Matron', 'Hostel Supervisor'],
  SECURITY: ['Security Guard', 'Security Supervisor', 'Night Watchman', 'Gate Officer'],
  KITCHEN: ['Head Chef', 'Cook', 'Catering Supervisor', 'Kitchen Assistant'],
  IT: ['ICT Technician', 'Network Administrator', 'Systems Support'],
  TRANSPORT: ['Driver', 'Transport Coordinator'],
  SPORTS: ['Sports Coordinator', 'Sports Master', 'Sports Captain'],
  MAINTENANCE: ['Maintenance Supervisor', 'Plumber', 'Electrician', 'Carpenter', 'General Maintenance Worker'],
  ADMIN_FINANCE: ['SDC Representative', 'Procurement Officer'],
  DINING: ['DH Captain'],
  HOUSE: ['House Master', 'House Captain'],
  PREFECTSHIP: ['Head Boy', 'Head Girl', 'Vice Head Boy', 'Vice Head Girl', 'Senior Prefect', 'Prefect', 'Class Monitor'],
  RELIGION: ['School Chaplain', 'Church Prefect'],
  LIBRARY_MGMT: ['Library Assistant'],
  STUDENT_LIBRARY: ['Student Librarian'],
  FARM_MGT: ['Farm Manager'],
  AGRI_ACADEMIC: ['Agriculture Teacher', 'Farm Assistant']
};
